source 'https://github.com/CocoaPods/Specs.git'

target 'PXFullBleedCollectionView' do
  pod "PXFullBleedCollectionView", :path => "../"
  pod "PXImageView"
end

target 'Tests' do
  pod "PXFullBleedCollectionView", :path => "../"
end
